version: '3'

services:
  django:
    image: python:3.10.12    
    container_name: django-service
    restart: always
    depends_on:
      - mysql
    command: > 
            sh -c "cd /home/django-service
            && pip install -r requirements.txt
            && python src/manage.py makemigrations
            && python src/manage.py migrate
            && python manage.py collectstatic
            && python src/manage.py runserver --insecure 10.6.0.10:8000"

    volumes:
      - .:/home/django-service

    ports:
      - "8000:8000"

    networks:
      custom-net:
        ipv4_address: 10.6.0.10

  mysql:
    image: mysql:8
    restart: always
    container_name: mysql-service

    environment:
      MYSQL_ROOT_PASSWORD: Maynex_2023** 
      MYSQL_DATABASE: efexChallenge 
      MYSQL_USER: administrator 
      MYSQL_PASSWORD: Maynex_2023** 
    volumes:
      - ./db-data:/var/lib/mysql

    ports:
      - "3307:3306"
    networks:
      custom-net:
        ipv4_address: 10.6.0.5


networks:
  custom-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
